import {
  FaSolarPanel,
  FaBuilding,
  FaIndustry,
  FaPlug,
  FaBatteryFull,
  FaSync,
  FaSun,
  FaTint as FaWater,
  FaUtensils,
  FaLightbulb,
  FaShower,
  FaBatteryThreeQuarters,
  FaBolt,
  FaShieldAlt,
  FaFileContract,
  FaTools,
  FaMapMarkerAlt,
  FaHandHoldingUsd,
  FaSnowflake,
  FaSoap,
  FaFire,
  FaTint,
  FaVideo,
  FaDollarSign,
  FaTrophy,
  FaLeaf,
  FaHome,
  FaUserTie,
  FaCertificate,
  FaMicrochip,
  FaStar,
  FaMoneyBill,
  FaTruck,
  FaMapMarkerAlt as FaLocation,
  FaHeadset,
  FaRulerCombined,
  FaPalette,
  FaFileInvoiceDollar,
  FaStamp
} from 'react-icons/fa';

export const iconMap = {
  'fa-solar-panel': FaSolarPanel,
  'fa-building': FaBuilding,
  'fa-industry': FaIndustry,
  'fa-plug': FaPlug,
  'fa-battery-full': FaBatteryFull,
  'fa-sync': FaSync,
  'fa-sun': FaSun,
  'fa-water': FaWater,
  'fa-bread-slice': FaUtensils,
  'fa-lightbulb': FaLightbulb,
  'fa-shower': FaShower,
  'fa-battery-three-quarters': FaBatteryThreeQuarters,
  'fa-bolt': FaBolt,
  'fa-spray-can-sparkles': FaBolt,
  'fa-shield-halved': FaShieldAlt,
  'fa-file-contract': FaFileContract,
  'fa-screwdriver-wrench': FaTools,
  'fa-route': FaMapMarkerAlt,
  'fa-hand-holding-dollar': FaHandHoldingUsd,
  'fa-snowflake': FaSnowflake,
  'fa-soap': FaSoap,
  'fa-utensils': FaUtensils,
  'fa-fire-burner': FaFire,
  'fa-droplet': FaTint,
  'fa-video': FaVideo,
  'fa-dollar-sign': FaDollarSign,
  'fa-trophy': FaTrophy,
  'fa-leaf': FaLeaf,
  'fa-house': FaHome,
  'fa-user-tie': FaUserTie,
  'fa-certificate': FaCertificate,
  'fa-microchip': FaMicrochip,
  'fa-money-bill': FaMoneyBill,
  'fa-truck-fast': FaTruck,
  'fa-location-dot': FaLocation,
  'fa-headset': FaHeadset,
  'fa-shield': FaShieldAlt,
  'fa-ruler-combined': FaRulerCombined,
  'fa-palette': FaPalette,
  'fa-file-invoice-dollar': FaFileInvoiceDollar,
  'fa-stamp': FaStamp,
  'fa-bolt-lightning': FaBolt
};
